### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/OpenMeme#12]
Memes need dark mode.

**Comment by nshanbhag20001412** [comment]
Hey, I want to work on this issue. Please assign it to me.

**Comment by shubhamcodez** [comment]
Sure go on.

**Comment by nshanbhag20001412** [comment]
hey i tried couldnt go forward.

**Comment by shubhamcodez** [comment]
> hey i tried couldnt go forward.

Fine

**Comment by camperjett** [comment]
Can you pls assign me this issue @shubhamcodez.

**Comment by Ujjwal-Gupta-web** [comment]
# How about this ??

![dark-mode-img](https://user-images.githubusercontent.com/67928331/135866081-6f83989c-7f8a-46fc-b16c-adad1332ecd8.png)

@shubhamcodez

**Comment by camperjett** [comment]
![image](https://user-images.githubusercontent.com/84286404/135871798-433bd32e-8766-44cd-bd54-23bb210c3f35.png)
here is my progress @shubhamcodez 
I may need a day or two to fix the issue. 
Meanwhile do not assign this to someone else please.
Thanks!

**Comment by shubhamcodez** [comment]
> # How about this ??
> ![dark-mode-img](https://user-images.githubusercontent.com/67928331/135866081-6f83989c-7f8a-46fc-b16c-adad1332ecd8.png)
> 
> @shubhamcodez
> 
> If you are good with it i will move ahead and work on toggle dark mode if needed.... if you just want default dark mode then i will do that in more structured way.

Can you coordinate with @camperjett and work together. I believe that'd be difficult for either one of you but let's see what's possible.

I see you have tried changing font colors and card color to adapt to changing in color, which is missing in @camperjett 's solution.

@Ujjwal-Gupta-web you can add your color blocks once he had added functionalities. 
Either way, let me know what you both think.

**Comment by camperjett** [comment]
@shubhamcodez I have resolved the issue
