### ISSUE TITLE
Moving Js/Jsx styles to a seperate .css file

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/OpenMeme#14]
Most are done, some need effort.

**Comment by Divyateja04** [comment]
I would like to work on this....can you assign this to me...also is it okay if I make the PR in october so that it can count in my hacktoberfest account

Also which which files do I need to extract the css from?

**Comment by shubhamcodez** [comment]
Sure. I expect it to be completed under hacktoberfest.
![Screenshot 2021-09-23 145918](https://user-images.githubusercontent.com/55784408/134484676-b1283014-45a1-4cbd-b1d2-742ba301aadc.png)

Take these from a .js/jsx file and put them into css files.
Once they are working fine, I'll merge the PR.

**Comment by Divyateja04** [comment]
um also one doubt, some sx elements have colors as initial and primary so can you give me any hint on how to convert them...like I have knowledge about react but never worked with these so asking

**Comment by shubhamcodez** [comment]
They were presets so, replace them with closest colors as that.

**Comment by Divyateja04** [comment]
Yeah okay, also one more doubt....in some cases after changing css also it's not being applied due to some other css coming from material ui...so do I use "!important" in these cases?

**Comment by shubhamcodez** [comment]
Yes.

**Comment by Divyateja04** [comment]
Sent the PR, can you check?

**Comment by shubhamcodez** [comment]
Sure.

**Comment by Divyateja04** [comment]
Also you should add hacktoberfest tag to your repo too, else they won't count in hacktoberfest...it shows repo not participating in hacktoberfest rn

**Comment by Divyateja04** [comment]
um you had asked for a ss right?

**Comment by shubhamcodez** [comment]
> um you had asked for a ss right?

Yes, but I pulled and ran it. It has been merged now.
Congratulations, Happy Hacking!
