### ISSUE TITLE
Make a footer for the site

### ISSUE THREAD

**Issue by jahgath** [shubhamcodez/OpenMeme#22]
![Capture](https://user-images.githubusercontent.com/53384211/134654700-9a522d6e-0cee-470c-88fe-7107206d394c.PNG)

**Comment by jahgath** [comment]
@shubhamcodez  after going through the cloned repo, I was not able to find the file with the links in the code. Can you help me locate the file ?

**Comment by shubhamcodez** [comment]
Okay, Jagath. I looked into it and saw that a footer and social Icons have not been put in the code of V2.
What you sent is a part of V1, We are no longer working on that.  You can make a footer and add icons there.
