### ISSUE TITLE
Clean the code

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/OpenMeme#24]
The code is just a messy and badly written. 
Improve and optimize it.

You may replace material UI elements with customised css. Just make the code clean and readable.

**Comment by BajraYeJoon** [comment]
Working on it!!!'

**Comment by tiger-yash** [comment]
Hello!
I would like to work on this issue, please assign it to me.

**Comment by tiger-yash** [comment]
@shubhamcodez you have not added `hacktoberfest` tag to the repository, it makes it easier as in that case you need not tag each and every PR or Issue.

**Comment by shubhamcodez** [comment]
> @shubhamcodez you have not added `hacktoberfest` tag to the repository, it makes it easier as in that case you need not tag each and every PR or Issue.

Is it correct now?
