### ISSUE TITLE
Add .prettierrc and .eslintrc config files to keep the codebase consistent

### ISSUE THREAD

**Issue by devstra** [shubhamcodez/OpenMeme#32]
It would probably be a good idea to add a dedicated `.prettierrc` file and `.eslintrc` file so that anyone contributing to the project uses the same formatting and conventions. I could set this up if you like the idea 😄 .

**Comment by devstra** [comment]
Also, introducing Typescript could be a good idea, before the project starts to get larger.

**Comment by shubhamcodez** [comment]
Sure. We can go ahead with the formatting idea.

I have never used Typescript. So, I have no idea how it works. It'll be difficult to maintain for me.

**Comment by devstra** [comment]
@shubhamcodez Okay, nevermind for Typescript then. Can you assign me this issue?

**Comment by shubhamcodez** [comment]
Sure.
