### ISSUE TITLE
Remove Extra Scrollbar

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/OpenMeme#40]
**Describe the bug**
There are 2 scrollbars, and one of them is altering Footer appearance.
It needs to be fixed ASAP.

**Expected behavior**
The footer should be visible and one scrollbar is expected.

**Comment by shivamchourasia4** [comment]
Hey there.
I am participating first time in Hacktoberfest this year and this seems a good place to start.
Can i fix this issue?

**Comment by shubhamcodez** [comment]
Sure, go on.
