### ISSUE TITLE
Write a proper ReadMe.md documentation.

### ISSUE THREAD

**Issue by shubhamcodez** [shubhamcodez/OpenMeme#9]
ReadMe was something we didn't pay attention during the time of making.
We would like to do it now.
so, create a beautiful, well-formated, grammatically correct and a detailed ReadMe as a contribution to our project.

**Comment by larapops** [comment]
I would like to work on it.

**Comment by devstra** [comment]
May I suggest https://readme.shaankhan.dev/ and https://www.makeareadme.com/ as a good place to start. I use these quite often for my own projects.

**Comment by shubhamcodez** [comment]
Thanks for the suggestions.
That's very helpful.
